server:
  port: 8080

spring:
  datasource:
    username: root
    password: Star2301#@&
    url: jdbc:mysql://49.232.103.232:3306/cloud_board?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 49.232.103.232
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 30000

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.sauzn.cloudboard.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
